### ISSUE TITLE
This is cool

### ISSUE THREAD

**Issue by vincens2005** [zsarge/OnCampusTweaks#2]
I just wanted to let you know I'm working on a related project that you might be interested in:
https://github.com/vincens2005/myschoolapp-better-client

**Comment by zsarge** [comment]
Interesting! I can tell you guys have put a lot of work into that.

Unfortunately, I don't think I can use it because my school doesn't give us passwords. 
My myschoolapp account is linked with my Microsoft account's sign in, so I don't actually have a password for myschoolapp.

Anyways, thanks for sharing.

**Comment by vincens2005** [comment]
that's interesting. anyways, thanks for checking it out. maybe in the future we can add in microsoft login
